### ISSUE TITLE
Not able to import modules

### ISSUE THREAD

**Issue by sasha-scale** [HazyResearch/domino#1]
I'm trying to run through the demo notebook: https://colab.research.google.com/github/HazyResearch/domino/blob/main/examples/01_intro.ipynb#scrollTo=v6FoBKhOtcHm

I am not able to import `from domino import embed` I believe due to the directory structure of the repo.  When I clone the repo locally I am able to do `from domino.domino import embed`

**Comment by seyuboglu** [comment]
Looks like the version on PyPI was out of date. I just updated it and confirmed that the notebook runs end to end on my side. Let me know if you're still unable to run it
