### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by bimsarapathiraja** [HazyResearch/domino#11]
The installation cells of the Colab demo doesn't work. As per the documentation we tried `!pip install domino` but still it didn't install. 
![image](https://github.com/HazyResearch/domino/assets/29068296/dde6c208-c4de-4498-8d74-6a75721fcce3)

**Comment by seyuboglu** [comment]
We used to be pinned to an old version of sklearn (see here #3), and it looks like the install for that version broke. The most recent update should've fixed the issue.
