### ISSUE TITLE
Unable to run slicer module

### ISSUE THREAD

**Issue by andisantos** [HazyResearch/domino#12]
Hello everyone!
I'm trying to use your work to split places365 dataset into domains, but I'm facing some troubles.
First, the command `pip install "domino[clip,text] @ git+htts://github.com/HazyResearch/domino@main"` throws an error, as pointed in #11 

So in order to use it, I tried to import just the module `domino._slice.mixture` in a testing notebook, but got an error on meerkat module:
![image](https://github.com/HazyResearch/domino/assets/13121643/29c3d091-dc42-41d3-b041-fb1c5c906166)

I then generated the clip embeds directly from their repository, commented the _embed imports in your code and an error during DominoSlicer fit function:
![image](https://github.com/HazyResearch/domino/assets/13121643/0bec2dc5-d6ef-4d4d-acfa-2d42f0baedd5)

I followed the directions in the class MixtureSlicer documentation to check the sizes of my inputs arrays and seems to be correct. Could you help me to debug this or give me some thoughts for where should I look to solve the problem? 

Thankyou!

**Comment by seyuboglu** [comment]
Just updated the installation so that we no longer depend on the deprecated version of sklearn. The install should work now.
