### ISSUE TITLE
imagenette is not being installed ? Error Below

### ISSUE THREAD

**Issue by allaabdella2** [HazyResearch/domino#5]
import os

dp = mk.datasets.get("imagenette")

# we'll only be using the validation data
dp = dp.lz[dp["split"] == "valid"]

-----------------------------------------------------------------------------------------
Downloading: 100%
1.56G/1.56G [00:42<00:00, 40.5MB/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-3-6cdd058db39e>](https://localhost:8080/#) in <module>()
      1 import os
      2 
----> 3 dp = mk.datasets.get("imagenette")
      4 
      5 # we'll only be using the validation data

4 frames
[/usr/local/lib/python3.7/dist-packages/meerkat/datasets/utils.py](https://localhost:8080/#) in extract(path, dst, extractor)
     22             return extractor.extract(path, dst)
     23         for extractor in Extractor.extractors:
---> 24             if extractor.is_extractable(path):
     25                 return extractor.extract(path, dst)
     26         raise ValueError("Extraction method not found for {}".format(path))

AttributeError: 'str' object has no attribute 'is_extractable'

**Comment by daavoo** [comment]
This is a bug introduced in `meerkat==0.2.5`. I have submitted a patch to https://github.com/robustness-gym/meerkat/pull/260

If you force install of `meerkat<0.2.5` the snippet will work

**Comment by Robdei** [comment]
Not a developer, but I found a workaround for this issue if you run the notebook locally:

1. Download imagenette from [https://github.com/fastai/imagenette](https://github.com/fastai/imagenette)
2. Put the downloaded imaginette folder in `~/.meerkat/datasets/imagenette/full/` (make sure the folder name is imaginette2)
3. You should now be able to run `dp = mk.datasets.get("imagenette")`

**Comment by seyuboglu** [comment]
This should be fixed in the most recent update -- let me know if the problem persists
