### ISSUE TITLE
Wiki word frequency file outdated

### ISSUE THREAD

**Issue by zorazrw** [HazyResearch/domino#7]
[This file](https://github.com/HazyResearch/domino/blob/ddc783bdbad4ce7f797e6c2b5000f1853c38f57e/domino/_describe/generate.py#L97) containing wiki word frequency seems to be unavailable now. I changed the path to this [new one](https://raw.githubusercontent.com/IlyaSemenov/wikipedia-word-frequency/master/results/enwiki-2022-08-29.txt) and it fixed the error.
It would be nice if we can prevent this sort of issue nonetheless.

**Comment by seyuboglu** [comment]
Thanks for pointing this out - just updated again to reflect the new link
